services:
  mc:
    image: itzg/minecraft-server:latest
    pull_policy: daily
    tty: true
    stdin_open: true
    restart: unless-stopped
    environment:
      EULA: "true"
      TYPE: "VANILLA"
      VERSION: "26.1"
      ONLINE_MODE: "false"
      MOTD: "Truest Survivor"
      RCON_PASSWORD: "${RCON_PASSWORD}"
    ports:
      - "25565:25565"
    volumes:
      - ./data/minecraft:/data

  viaproxy:
    image: ghcr.io/viaversion/viaproxy:latest
    restart: unless-stopped
    depends_on:
      - mc
    ports:
      - "25568:25568"
    volumes:
      - ./data/viaproxy:/app/run

  geyser:
    build:
      context: .
      dockerfile: geyser.Dockerfile
    restart: unless-stopped
    depends_on:
      - viaproxy
    ports:
      - "19132:19132/udp"
    volumes:
      - ./data/geyser:/data

  backup:
    image: itzg/mc-backup
    restart: unless-stopped
    depends_on:
      - mc
    environment:
      BACKUP_INTERVAL: "24h"
      RCON_HOST: mc
      RCON_PORT: "25575"
      RCON_PASSWORD: "${RCON_PASSWORD}"
      DEST_DIR: /backups
      KEEP_COUNT: "7"
    volumes:
      - ./data/minecraft:/data:ro
      - ./data/backups:/backups
